spring:
  application:
    name: @name@
server:
  port: 8081
eureka:
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/
  instance:
    hostname: localhost
    port: 1111
    appname: @name@
management:
  security:
    enabled: false